blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/SUUwAqh6Q
    about: Ask questions, get help, or chat with other BIT developers and users on our Discord server.
