package me.rerere.workspace

import java.io.File
import java.nio.file.Files

class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        val etcDir = File(linuxDir, "etc")
        if (etcDir.isDirectory) {
            ensureRootfsDns(etcDir, options.nameservers)
            ensureHosts(etcDir, options.hostname)
            ensureHostname(etcDir, options.hostname)
            ensureLocale(etcDir, options.locale)
            ensureGroupNames(etcDir, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
            ensureEnvironment(linuxDir, etcDir)
        }
        ensureTempDirs(linuxDir)
        ensureMergedUsrLinks(linuxDir)
        ensureShellEntrypoints(linuxDir)
        ensureAptAndDpkgConfigs(linuxDir)
        ensurePipConfig(linuxDir)
    }

    private fun ensureRootfsDns(
        etcDir: File,
        nameservers: List<String>,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")
        val shouldWrite = when {
            Files.isSymbolicLink(resolvConf.toPath()) -> true
            !resolvConf.exists() -> true
            !resolvConf.isFile -> true
            else -> resolvConf.readText()
                .lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .none { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in LOCAL_RESOLVERS
                }
        }
        if (!shouldWrite) return

        if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
            resolvConf.delete()
        }

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }

        resolvConf.writeText(
            buildString {
                appendLine("# Generated by RikkaHub workspace.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
    }

    private fun ensureHosts(etcDir: File, hostname: String) {
        val hosts = File(etcDir, "hosts")
        val lines = if (hosts.isFile) hosts.readLines() else emptyList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hosts.exists() && hosts.length() > 0 && !hosts.readText().endsWith('\n')) {
                    appendLine()
                }
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensureHostname(etcDir: File, hostname: String) {
        val target = File(etcDir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(etcDir: File, locale: String) {
        val defaultDir = File(etcDir, "default").apply { mkdirs() }
        val target = File(defaultDir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensureGroupNames(etcDir: File, groupIds: List<Long>) {
        val target = File(etcDir, "group")
        if (!target.exists()) {
            target.writeText("root:x:0:\n")
        }
        val lines = target.readLines().toMutableList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return

        target.appendText(
            buildString {
                if (target.length() > 0 && !target.readText().endsWith('\n')) {
                    appendLine()
                }
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensureEnvironment(linuxDir: File, etcDir: File) {
        val envContent = """
            DEBIAN_FRONTEND=noninteractive
            DEBCONF_NONINTERACTIVE_SEEN=true
            LANG=C.UTF-8
            LC_ALL=C.UTF-8
            PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        """.trimIndent() + "\n"

        File(etcDir, "environment").writeText(envContent)

        val profileDir = File(etcDir, "profile.d").apply { mkdirs() }
        File(profileDir, "00-bit-proot.sh").writeText("""
            export DEBIAN_FRONTEND=noninteractive
            export DEBCONF_NONINTERACTIVE_SEEN=true
            export LANG=C.UTF-8
            export LC_ALL=C.UTF-8
            export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        """.trimIndent() + "\n")

        val rootDir = File(linuxDir, "root").apply { mkdirs() }
        listOf(".bashrc", ".profile").forEach { file ->
            val target = File(rootDir, file)
            val exportLine = "export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true"
            if (!target.exists()) {
                target.writeText("$exportLine\n")
            } else if (!target.readText().contains("DEBIAN_FRONTEND")) {
                target.appendText("\n$exportLine\n")
            }
        }

        // Preconfigure timezone so tzdata doesn't prompt
        File(etcDir, "timezone").writeText("UTC\n")
    }

    private fun ensureTempDirs(linuxDir: File) {
        listOf("tmp", "var/tmp", "root", "workspace").forEach { path ->
            File(linuxDir, path).mkdirs()
        }
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp"), File(linuxDir, "workspace")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(linuxDir, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun ensureShellEntrypoints(linuxDir: File) {
        val usrBinDir = File(linuxDir, "usr/bin")
        val binDir = File(linuxDir, "bin")
        val sh = File(binDir, "sh")
        if (sh.exists()) return

        val source = listOf(
            File(usrBinDir, "sh"),
            File(usrBinDir, "bash"),
            File(binDir, "bash"),
        ).firstOrNull { it.isFile } ?: return
        if (runCatching { sh.canonicalFile == source.canonicalFile }.getOrDefault(false)) return

        sh.parentFile?.mkdirs()
        runCatching {
            val parent = sh.parentFile ?: return@runCatching
            val relativeTarget = if (Files.isSymbolicLink(parent.toPath())) {
                // If bin is a symlink to usr/bin, resolve the target relative to the canonical path
                parent.canonicalFile.toPath().relativize(source.toPath())
            } else {
                parent.toPath().relativize(source.toPath())
            }
            Files.createSymbolicLink(sh.toPath(), relativeTarget)
        }.recoverCatching {
            source.copyTo(sh, overwrite = true)
            sh.setReadable(source.canRead(), false)
            sh.setWritable(source.canWrite(), true)
            sh.setExecutable(source.canExecute(), false)
        }.getOrNull()
    }

    private fun ensureAptAndDpkgConfigs(linuxDir: File) {
        val etcDir = File(linuxDir, "etc")
        if (!etcDir.isDirectory) return
        
        // Prevent dpkg from calling sync() which can be extremely slow or fail in proot on Android
        val dpkgCfgDir = File(etcDir, "dpkg/dpkg.cfg.d")
        dpkgCfgDir.mkdirs()
        File(dpkgCfgDir, "force-unsafe-io").writeText(
            """
            force-unsafe-io
            force-confdef
            force-confold
            """.trimIndent() + "\n"
        )

        // Prevent services from starting during package installation
        val sbinDirs = listOf(File(linuxDir, "usr/sbin"), File(linuxDir, "sbin"), File(linuxDir, "usr/bin"), File(linuxDir, "bin"))
        sbinDirs.forEach { it.mkdirs() }

        val exit101Script = "#!/bin/sh\nexit 101\n"
        val exit0Script = "#!/bin/sh\nexit 0\n"

        // Mock policy-rc.d to deny service startup
        listOf("usr/sbin/policy-rc.d", "sbin/policy-rc.d").forEach { relPath ->
            val file = File(linuxDir, relPath)
            if (!file.exists()) {
                file.writeText(exit101Script)
                file.setExecutable(true, false)
            }
        }

        // Mock daemon helpers that fail in PRoot
        listOf(
            "usr/bin/systemctl",
            "bin/systemctl",
            "usr/sbin/invoke-rc.d",
            "sbin/invoke-rc.d",
            "usr/sbin/service",
            "sbin/service",
            "usr/sbin/initctl",
            "sbin/initctl",
            "usr/sbin/start-stop-daemon",
            "sbin/start-stop-daemon"
        ).forEach { relPath ->
            val file = File(linuxDir, relPath)
            if (!file.exists()) {
                file.writeText(exit0Script)
                file.setExecutable(true, false)
            }
        }

        // Disable apt-get sandboxing and fix http methods to avoid _apt and pipeline issues in proot
        val aptConfDir = File(etcDir, "apt/apt.conf.d")
        aptConfDir.mkdirs()
        File(aptConfDir, "99proot").writeText(
            """
            APT::Sandbox::User "root";
            APT::Get::Assume-Yes "true";
            Acquire::http::Pipeline-Depth "0";
            Acquire::http::No-Cache "true";
            Acquire::BrokenProxy "true";
            Acquire::http::Timeout "120";
            Acquire::https::Timeout "120";
            DPkg::Options {
               "--force-unsafe-io";
               "--force-confdef";
               "--force-confold";
            };
            DPkg::Post-Invoke { "dpkg --configure -a || true"; };
            """.trimIndent() + "\n"
        )

        // Repair /var/lib/dpkg/status if corrupted by chained link2symlink
        val dpkgDir = File(linuxDir, "var/lib/dpkg")
        if (dpkgDir.isDirectory) {
            val statusFile = File(dpkgDir, "status")
            if (Files.isSymbolicLink(statusFile.toPath()) || !statusFile.exists()) {
                val realStatusContent = runCatching {
                    if (statusFile.exists()) statusFile.readBytes()
                    else dpkgDir.listFiles()?.firstOrNull { it.name.startsWith(".l2s.status") }?.readBytes()
                }.getOrNull()

                if (realStatusContent != null && realStatusContent.isNotEmpty()) {
                    // Delete all status symlinks and l2s files
                    dpkgDir.listFiles()?.filter { it.name.startsWith(".l2s.") || it.name.startsWith("status") }?.forEach {
                        runCatching { Files.deleteIfExists(it.toPath()) }
                    }
                    // Write status as a fresh plain file
                    statusFile.writeBytes(realStatusContent)
                }
            } else {
                // Delete stale status-old / status-new if they are symlinks or incomplete
                File(dpkgDir, "status-old").let { if (Files.isSymbolicLink(it.toPath())) runCatching { Files.deleteIfExists(it.toPath()) } }
                File(dpkgDir, "status-new").let { if (Files.isSymbolicLink(it.toPath())) runCatching { Files.deleteIfExists(it.toPath()) } }
            }
        }

        // Clean stale lock files from previous aborted runs
        listOf(
            "var/lib/dpkg/lock",
            "var/lib/dpkg/lock-frontend",
            "var/lib/apt/lists/lock",
            "var/cache/apt/archives/lock"
        ).forEach { lockPath ->
            val lockFile = File(linuxDir, lockPath)
            if (lockFile.exists()) {
                runCatching { lockFile.delete() }
            }
        }
    }

    private fun ensurePipConfig(linuxDir: File) {
        val etcDir = File(linuxDir, "etc")
        if (etcDir.isDirectory) {
            val pipConf = File(etcDir, "pip.conf")
            pipConf.writeText("[global]\nbreak-system-packages = true\n")
        }

        val rootPipDir = File(linuxDir, "root/.config/pip")
        rootPipDir.mkdirs()
        File(rootPipDir, "pip.conf").writeText("[global]\nbreak-system-packages = true\n")

        // Remove EXTERNALLY-MANAGED markers across python versions so pip install works seamlessly
        val usrLib = File(linuxDir, "usr/lib")
        if (usrLib.isDirectory) {
            usrLib.listFiles()?.filter { it.name.startsWith("python3") && it.isDirectory }?.forEach { pyDir ->
                val marker = File(pyDir, "EXTERNALLY-MANAGED")
                if (marker.exists()) {
                    runCatching { marker.delete() }
                }
            }
        }
    }

    private fun ensureMergedUsrLinks(linuxDir: File) {
        ensureMergedUsrLink(linuxDir, "bin", "usr/bin")
        ensureMergedUsrLink(linuxDir, "sbin", "usr/sbin")
        ensureMergedUsrLink(linuxDir, "lib", "usr/lib")
        ensureMergedUsrLink(linuxDir, "lib64", "usr/lib64")
    }

    private fun ensureMergedUsrLink(
        linuxDir: File,
        linkPath: String,
        targetPath: String,
    ) {
        val link = File(linuxDir, linkPath)
        val target = File(linuxDir, targetPath)
        if (!target.exists()) return
        if (Files.isSymbolicLink(link.toPath())) return

        if (!link.exists()) {
            link.parentFile?.mkdirs()
            runCatching {
                Files.createSymbolicLink(link.toPath(), File(targetPath).toPath())
            }.recoverCatching {
                if (target.isDirectory) {
                    target.copyRecursively(link, overwrite = true)
                } else {
                    target.copyTo(link, overwrite = true)
                    link.setReadable(target.canRead(), false)
                    link.setWritable(target.canWrite(), true)
                    link.setExecutable(target.canExecute(), false)
                }
            }.getOrNull()
            return
        }

        if (link.isDirectory && target.isDirectory) {
            val tempLink = File(link.parentFile, "${link.name}.rikkahub-tmp")
            runCatching {
                Files.createSymbolicLink(tempLink.toPath(), File(targetPath).toPath())
            }.onSuccess {
                link.listFiles()?.forEach { child ->
                    val dest = File(target, child.name)
                    if (!dest.exists()) {
                        child.renameTo(dest)
                    }
                }
                link.deleteRecursively()
                tempLink.renameTo(link)
            }.onFailure {
                tempLink.delete()
            }
        }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val MAX_DNS_SERVERS = 3
        private const val DEFAULT_HOSTNAME = "localhost"
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )
        private val DEFAULT_DNS_SERVERS = listOf(
            "1.1.1.1",
            "8.8.8.8",
            "223.5.5.5",
        )
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
)
