package com.bit.api.util

import com.bit.api.ChatMessage
import com.bit.api.Participant
import com.bit.api.Constants

fun prepareMessages(messages: List<ChatMessage>, maxUserMessages: Int): List<ChatMessage> {
    return validateToolMessages(mergeConsecutiveSameRole(limitContext(messages, maxUserMessages)))
}

fun projectAssistantImagesToLatestUserMessage(
    messages: List<ChatMessage>,
    includeImages: Boolean
): List<ChatMessage> {
    if (messages.isEmpty()) return messages

    val latestUserIndex = messages.indexOfLast { it.isNormalUserMessage() }
    val generatedImages = if (includeImages && latestUserIndex >= 0) {
        messages
            .asSequence()
            .take(latestUserIndex)
            .filter { it.isNormalAssistantMessage() && it.images.isNotEmpty() }
            .lastOrNull()
            ?.images
            ?.filter { it.isNotBlank() }
            .orEmpty()
    } else {
        emptyList()
    }

    var changed = false
    val projected = messages.mapIndexed { index, msg ->
        var next = msg
        if (msg.isNormalAssistantMessage() && msg.images.isNotEmpty()) {
            next = next.copy(images = emptyList())
            changed = true
        }
        if (index == latestUserIndex && generatedImages.isNotEmpty()) {
            next = next.copy(
                text = addGeneratedImageContextNote(next.text, generatedImages.size),
                images = (generatedImages + next.images).distinct()
            )
            changed = true
        }
        next
    }

    return if (changed) projected else messages
}

private fun ChatMessage.isNormalUserMessage(): Boolean =
    participant == Participant.USER && !isToolProtocolMessage()

private fun ChatMessage.isNormalAssistantMessage(): Boolean =
    participant == Participant.MODEL && !isToolProtocolMessage()

private fun ChatMessage.isToolProtocolMessage(): Boolean =
    id.startsWith(Constants.TOOL_MSG_PREFIX) || id.startsWith(Constants.RESULT_MSG_PREFIX)

private fun addGeneratedImageContextNote(text: String, imageCount: Int): String {
    val note = if (imageCount == 1) {
        "[Visual context: the first attached image was generated by the assistant earlier in this conversation.]"
    } else {
        "[Visual context: the first $imageCount attached images were generated by the assistant earlier in this conversation.]"
    }
    return if (text.isBlank()) note else "$note\n\n$text"
}

fun mergeConsecutiveSameRole(messages: List<ChatMessage>): List<ChatMessage> {
    if (messages.isEmpty()) return messages
    val result = mutableListOf<ChatMessage>()
    var i = 0
    while (i < messages.size) {
        val current = messages[i]
        val isTool = current.id.startsWith(Constants.TOOL_MSG_PREFIX) ||
            current.id.startsWith(Constants.RESULT_MSG_PREFIX)
        if (isTool) {
            result.add(current)
            i++
            continue
        }
        var j = i + 1
        while (j < messages.size) {
            val next = messages[j]
            val nextIsTool = next.id.startsWith(Constants.TOOL_MSG_PREFIX) ||
                next.id.startsWith(Constants.RESULT_MSG_PREFIX)
            if (nextIsTool || next.participant != current.participant) break
            j++
        }
        if (j == i + 1) {
            result.add(current)
        } else {
            val merged = messages.subList(i, j)
            val mergedText = merged.joinToString("\n") { it.text }
            val mergedImages = merged.flatMap { it.images }
            result.add(current.copy(text = mergedText, images = mergedImages))
        }
        i = j
    }
    return result
}

fun validateToolMessages(messages: List<ChatMessage>): List<ChatMessage> {
    val result = mutableListOf<ChatMessage>()
    var i = 0
    while (i < messages.size) {
        val msg = messages[i]
        when {
            msg.id.startsWith(Constants.TOOL_MSG_PREFIX) -> {
                val resultMessages = mutableListOf<ChatMessage>()
                var j = i + 1
                while (j < messages.size && messages[j].id.startsWith(Constants.RESULT_MSG_PREFIX)) {
                    resultMessages.add(messages[j])
                    j++
                }
                if (resultMessages.isNotEmpty()) {
                    result.add(msg)
                    result.addAll(fixToolIds(msg, resultMessages))
                    i = j
                } else {
                    i++ // orphan tool_ — drop
                }
            }
            msg.id.startsWith(Constants.RESULT_MSG_PREFIX) -> {
                i++ // orphan result_ — drop
            }
            else -> {
                result.add(msg)
                i++
            }
        }
    }
    return result
}

private fun fixToolIds(
    toolMsg: ChatMessage,
    resultMessages: List<ChatMessage>
): List<ChatMessage> {
    val toolSegments = toolMsg.segments?.filter { it.type == "tool" } ?: return resultMessages
    if (toolSegments.isEmpty()) return resultMessages
    val useIds = toolSegments.mapNotNull { it.toolCallId }
    if (useIds.size != toolSegments.size) return resultMessages

    return resultMessages.mapIndexed { idx, resultMsg ->
        if (idx >= useIds.size) return@mapIndexed resultMsg
        val correctId = useIds[idx]

        val fixedSegments = resultMsg.segments?.map { seg ->
            if (seg.type == "tool" && seg.toolCallId != correctId) seg.copy(toolCallId = correctId) else seg
        }
        val fixedToolCall = resultMsg.toolCall?.let { tc ->
            if (tc.toolCallId != correctId) tc.copy(toolCallId = correctId) else tc
        }
        if (fixedSegments != resultMsg.segments || fixedToolCall != resultMsg.toolCall) {
            resultMsg.copy(segments = fixedSegments, toolCall = fixedToolCall)
        } else resultMsg
    }
}
